### ISSUE TITLE
tagging format

### ISSUE THREAD

**Issue by ulvida** [stuvusIT/sympa#10]
I saw you tagged a [v0.1.0](https://github.com/stuvusIT/sympa/tree/0.1.0). Great!

However, AFAIK, [git syntax](https://git-scm.com/book/en/v2/Git-Basics-Tagging) establishes that versions tagging must start with a "v". This is needed to be seen in Ansible Galaxy.

**Comment by SlothOfAnarchy** [comment]
https://github.com/stuvusIT/sympa/releases/tag/v0.1.0
